Fix #7 Add tailwind css to project
rt4914/KlinicCon-Frontend pull request #18
Opened 2024-08-10 16:06 UTC by rray524

Fix #7 Add tailwind css to project

2024-08-10 16:22 UTC, rt4914 requested changes
One minor change

2024-08-10 16:22 UTC, rt4914 commented on tailwind.config.js
> +export const content = ["./src/**/*.{js,jsx,ts,tsx}"];
Include `"./index.html",` too in this.

2024-08-10 16:59 UTC, rray524 commented on tailwind.config.js
> +export const content = ["./src/**/*.{js,jsx,ts,tsx}"];
@rt4914 added. thanks.

2024-08-11 06:15 UTC, rt4914 approved these changes
LGTM, Thanks.

2024-08-11 06:15 UTC, merged