Fix #8 : Add story book
rt4914/KlinicCon-Frontend pull request #19
Opened 2024-08-10 16:23 UTC by rray524

Fix #8 : Add story book

2024-08-10 16:29 UTC, rt4914 requested changes
For now this is fin.e But we should add an issue to mention steps on how to run storybook in Readme.md file

Once that issue is filed, mention it here so that I can approve this and we can merge.

2024-08-10 16:29 UTC, rt4914 commented on .gitignore
> +*storybook.log
Add blank line here at the end

2024-08-10 17:56 UTC, rray524 commented on .gitignore
> +*storybook.log
added.

2024-08-10 17:57 UTC, rray524 commented
> For now this is fin.e But we should add an issue to mention steps on how to run storybook in Readme.md file
> 
> Once that issue is filed, mention it here so that I can approve this and we can merge.

I updated read me with a proper running command, which can be copied from it and a small intro of storybook. Thanks @rt4914

2024-08-11 11:53 UTC, rt4914 commented
> > For now this is fin.e But we should add an issue to mention steps on how to run storybook in Readme.md file
> > Once that issue is filed, mention it here so that I can approve this and we can merge.
> 
> I updated read me with a proper running command, which can be copied from it and a small intro of storybook. Thanks @rt4914

@rray524 Where did you update the README ? I am unable to see that. 


Also README.md file is currently getting developed so that's why I have mentioned that you should create an issue once that README.md file gets created correctly, then we can mention the updated steps in that file by create a new PR.

Also, merge your branch with latest main to resolve merge conflicts.

2024-08-11 12:32 UTC, rray524 commented
> > > For now this is fin.e But we should add an issue to mention steps on how to run storybook in Readme.md file
> > > Once that issue is filed, mention it here so that I can approve this and we can merge.
> > 
> > 
> > I updated read me with a proper running command, which can be copied from it and a small intro of storybook. Thanks @rt4914
> 
> @rray524 Where did you update the README ? I am unable to see that.
> 
> Also README.md file is currently getting developed so that's why I have mentioned that you should create an issue once that README.md file gets created correctly, then we can mention the updated steps in that file by create a new PR.
> 
> Also, merge your branch with latest main to resolve merge conflicts.

@rt4914 here is the readme.md file where I added how to run storybook & intro of storybook:
https://github.com/rt4914/KlinicCon-Frontend/blob/8614947832d2b7aecb809fea72232487ff0b9765/README.md

2024-08-16 06:17 UTC, rt4914 commented
> > > > For now this is fin.e But we should add an issue to mention steps on how to run storybook in Readme.md file
> > > > Once that issue is filed, mention it here so that I can approve this and we can merge.
> > > 
> > > 
> > > I updated read me with a proper running command, which can be copied from it and a small intro of storybook. Thanks @rt4914
> > 
> > 
> > @rray524 Where did you update the README ? I am unable to see that.
> > Also README.md file is currently getting developed so that's why I have mentioned that you should create an issue once that README.md file gets created correctly, then we can mention the updated steps in that file by create a new PR.
> > Also, merge your branch with latest main to resolve merge conflicts.
> 
> @rt4914 here is the readme.md file where I added how to run storybook & intro of storybook: https://github.com/rt4914/KlinicCon-Frontend/blob/8614947832d2b7aecb809fea72232487ff0b9765/README.md so I am removing the steps now and will later, once readme.md full get resolved. **Removed merging conflict too.** Thanks.

@rray524 So if you look at that README.md file, its just a sample file and because of that I was suggesting you to create an issue. But now we have merged/updated the README.md file so you can add this correctly directly in README.md file
https://github.com/rt4914/KlinicCon-Frontend?tab=readme-ov-file#installation
Please add this correctly in installation-frontend section clearly mentioning that its a an optional step to run a storybook.

Also, I was unable to review it because you never assigned it to me. So please make sure you `Assignee` PRs to me.

2024-08-16 07:39 UTC, rray524 commented
> > > > > For now this is fin.e But we should add an issue to mention steps on how to run storybook in Readme.md file
> > > > > Once that issue is filed, mention it here so that I can approve this and we can merge.
> > > > 
> > > > 
> > > > I updated read me with a proper running command, which can be copied from it and a small intro of storybook. Thanks @rt4914
> > > 
> > > 
> > > @rray524 Where did you update the README ? I am unable to see that.
> > > Also README.md file is currently getting developed so that's why I have mentioned that you should create an issue once that README.md file gets created correctly, then we can mention the updated steps in that file by create a new PR.
> > > Also, merge your branch with latest main to resolve merge conflicts.
> > 
> > 
> > @rt4914 here is the readme.md file where I added how to run storybook & intro of storybook: https://github.com/rt4914/KlinicCon-Frontend/blob/8614947832d2b7aecb809fea72232487ff0b9765/README.md so I am removing the steps now and will later, once readme.md full get resolved. **Removed merging conflict too.** Thanks.
> 
> @rray524 So if you look at that README.md file, its just a sample file and because of that I was suggesting you to create an issue. But now we have merged/updated the README.md file so you can add this correctly directly in README.md file https://github.com/rt4914/KlinicCon-Frontend?tab=readme-ov-file#installation Please add this correctly in installation-frontend section clearly mentioning that its a an optional step to run a storybook.
> 
> Also, I was unable to review it because you never assigned it to me. So please make sure you `Assignee` PRs to me.

hi @rt4914 I have assigned you to review. I have made changes on readme.md . thanks

2024-08-20 08:09 UTC, rt4914 approved these changes
LGTM, Thanks.

2024-08-20 08:09 UTC, merged